### ISSUE TITLE
Expand renaming to all file types

### ISSUE THREAD

**Issue by amot-dev** [amot-dev/timestamp#10]
Right now, files are excluded if they don't have exif or xmp tags. Would be nice to allow all files and use inode data for other files.

**Comment by amot-dev** [comment]
My current idea for this is to have a config (input or default location) that determines included file types and their preference, with an option to fallback to inode if a file doesn't have the expected type (and show a warning for it). Something like this:

exif: jpg, jpeg
xmp: mp4, avi, mkv, mov
inode: txt

inode_fallback: true

**Comment by amot-dev** [comment]
YAML seems like a better option here. Perhaps something like this:

```yaml
# Date format for displaying dates
date_format: "%Y-%m-%d %H:%M:%S"

# Define groups of file extensions
extension_groups:
  image:
    - "jpg"
    - "jpeg"
  video:
    - "mp4"
    - "avi"
    - "mkv"
    - "mov"

# Define tag mappings for extension groups
tags_for:
  image:
    - "Exif.Photo.DateTimeOriginal"
    - "inode.Modified"
  video:
    - "Xmp.video.ModificationDate"
    - "Xmp.video.CreateDate"
    - "inode.Modified"

```
